####################################
#      Simple Ticket Manager       #
#        Made by Jwoolley          #
####################################

#Set to true if you wish to allow other people to close tickets,
#Set to false if you only want the person who claimed it to be able to close it
allowotherstoclose: false

#Displays about open tickets when admins join the server
#Set to true to get messages, false to disable them
adminmessages: true

#Display to all staff when a ticket has been closed
#Set to true if you want staff to get notices
#Set to false if you don't want notices on close
closenotice: false

#Support for multiple servers
#Uses server name from server.properties
bungeecord: false

#Log the amount of players online with each ticket
players: false

#Maximum number of tickets a player can claim
maxtickets: 3

#How often the database should be updated
#The amount of seconds you want
updateTime: 60

#Set to true if you wish to use MySQL
mysql: true

#Connection details for MySQL
hostname: 127.0.0.1
port: 3306
database: minecatsTickets
username: WillyBillyChangeAName
password: 1-2-3-4-5-andChangeTheCombinationOnMyLuggage
